# Default values for game2048.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

appName: "game2048"
replicaCount: 2
image:
  repository: 714546234903.dkr.ecr.ap-northeast-2.amazonaws.com/kepler2048
  pullPolicy: IfNotPresent
  tag: "v1"
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
podAnnotations: {}
maxSurge: 34%
maxUnavailable: 0%
service:
  type: ClusterIP
  port: 8080
ingress:
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/load-balancer-name: kepler-app-alb
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/subnets: subnet-06f208d82c249e90a, subnet-0c739ad08e6263488
  ingressRule:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: game2048
                port:
                  number: 8080
resources:
# We usually recommend not to specify default resources and to leave this as a conscious
# choice for the user. This also increases chances charts run on environments with little
# resources, such as Minikube. If you do want to specify resources, uncomment the following
# lines, adjust them as necessary, and remove the curly braces after 'resources:'.
 limits:
   cpu: 500m
   memory: 128Mi
 requests:
   cpu: 500m
   memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 20
  # targetMemoryUtilizationPercentage: 80
#nodeSelector:
#  nodeType: service-2023
tolerations:
  - key: service
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"
affinity: {}
